<?xml version="1.0" encoding="UTF-8"?>
<!--
This file was generated by Altova MapForce 2008r2

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce Documentation for further details.
http://www.altova.com/mapforce
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="urn:hl7-org:v2xml" exclude-result-prefixes="xs">
	<xsl:output method="xml" encoding="UTF-8" indent="yes" />
	<xsl:template match="/message">
		<MDM_T02>
			<xsl:variable name="Vvar1292_const" select="1"/>
			<MSH>
				<MSH.1>
					<xsl:value-of select="'|'"/>
				</MSH.1>
				<MSH.2>
					<xsl:value-of select="'^~\&amp;'"/>
				</MSH.2>
				<MSH.3>
					<xsl:for-each select="DatiFissi">
						<xsl:for-each select="SendingApplication">
							<xsl:variable name="Vvar1264_SendingApplication_anySimpleType" select="."/>
							<HD.1>
								<xsl:value-of select="$Vvar1264_SendingApplication_anySimpleType"/>
							</HD.1>
						</xsl:for-each>
					</xsl:for-each>
				</MSH.3>
				<MSH.4>
					<xsl:for-each select="DatiFissi">
						<xsl:for-each select="SendingFacility">
							<xsl:variable name="Vvar1271_SendingFacility_anySimpleType" select="."/>
							<HD.1>
								<xsl:value-of select="$Vvar1271_SendingFacility_anySimpleType"/>
							</HD.1>
						</xsl:for-each>
					</xsl:for-each>
				</MSH.4>
				<MSH.5>
					<xsl:for-each select="DatiFissi">
						<xsl:for-each select="ReceivingApplication">
							<xsl:variable name="Vvar1278_ReceivingApplication_anySimpleType" select="."/>
							<HD.1>
								<xsl:value-of select="$Vvar1278_ReceivingApplication_anySimpleType"/>
							</HD.1>
						</xsl:for-each>
					</xsl:for-each>
				</MSH.5>
				<MSH.6>
					<xsl:for-each select="DatiFissi">
						<xsl:for-each select="ReceivingFacility">
							<xsl:variable name="Vvar1285_ReceivingFacility_anySimpleType" select="."/>
							<HD.1>
								<xsl:value-of select="$Vvar1285_ReceivingFacility_anySimpleType"/>
							</HD.1>
						</xsl:for-each>
					</xsl:for-each>
				</MSH.6>
				<MSH.7>
					<TS.1>
						<xsl:for-each select="DatiCalcolati">
							<xsl:for-each select="DataMessaggio">
								<xsl:variable name="Vvar1290_DataMessaggio_anySimpleType" select="."/>
								<DTTM.1>
									<xsl:value-of select="substring(string($Vvar1290_DataMessaggio_anySimpleType), number($Vvar1292_const), number(4))"/>
								</DTTM.1>
							</xsl:for-each>
						</xsl:for-each>
						<xsl:for-each select="DatiCalcolati">
							<xsl:for-each select="DataMessaggio">
								<xsl:variable name="Vvar1300_DataMessaggio_anySimpleType" select="."/>
								<DTTM.2>
									<xsl:value-of select="substring(string($Vvar1300_DataMessaggio_anySimpleType), number(5), number(2))"/>
								</DTTM.2>
							</xsl:for-each>
						</xsl:for-each>
						<xsl:for-each select="DatiCalcolati">
							<xsl:for-each select="DataMessaggio">
								<xsl:variable name="Vvar1310_DataMessaggio_anySimpleType" select="."/>
								<DTTM.3>
									<xsl:value-of select="substring(string($Vvar1310_DataMessaggio_anySimpleType), number(7), number(2))"/>
								</DTTM.3>
							</xsl:for-each>
						</xsl:for-each>
						<xsl:for-each select="DatiCalcolati">
							<xsl:for-each select="DataMessaggio">
								<xsl:variable name="Vvar1320_DataMessaggio_anySimpleType" select="."/>
								<DTTM.4>
									<xsl:value-of select="substring(string($Vvar1320_DataMessaggio_anySimpleType), number(9), number(2))"/>
								</DTTM.4>
							</xsl:for-each>
						</xsl:for-each>
						<xsl:for-each select="DatiCalcolati">
							<xsl:for-each select="DataMessaggio">
								<xsl:variable name="Vvar1330_DataMessaggio_anySimpleType" select="."/>
								<DTTM.5>
									<xsl:value-of select="substring(string($Vvar1330_DataMessaggio_anySimpleType), number(11), number(2))"/>
								</DTTM.5>
							</xsl:for-each>
						</xsl:for-each>
						<xsl:for-each select="DatiCalcolati">
							<xsl:for-each select="DataMessaggio">
								<xsl:variable name="Vvar1340_DataMessaggio_anySimpleType" select="."/>
								<DTTM.6>
									<xsl:value-of select="substring(string($Vvar1340_DataMessaggio_anySimpleType), number(13), number(2))"/>
								</DTTM.6>
							</xsl:for-each>
						</xsl:for-each>
					</TS.1>
				</MSH.7>
				<MSH.9>
					<xsl:for-each select="DatiCalcolati">
						<xsl:for-each select="TipoMessaggio">
							<xsl:variable name="Vvar1352_TipoMessaggio_anySimpleType" select="."/>
							<MSG.1>
								<xsl:value-of select="$Vvar1352_TipoMessaggio_anySimpleType"/>
							</MSG.1>
						</xsl:for-each>
					</xsl:for-each>
				</MSH.9>
				<xsl:for-each select="DatiCalcolati">
					<xsl:for-each select="DataMessaggio">
						<xsl:variable name="Vvar1359_DataMessaggio_anySimpleType" select="."/>
						<MSH.10>
							<xsl:value-of select="$Vvar1359_DataMessaggio_anySimpleType"/>
						</MSH.10>
					</xsl:for-each>
				</xsl:for-each>
				<MSH.11>
					<PT.1>
						<xsl:value-of select="'P'"/>
					</PT.1>
				</MSH.11>
				<MSH.12>
					<VID.1>
						<xsl:value-of select="'2.5'"/>
					</VID.1>
				</MSH.12>
			</MSH>
			<EVN>
				<EVN.2>
					<TS.1>
						<xsl:for-each select="DatiCalcolati">
							<xsl:for-each select="DataMessaggio">
								<xsl:variable name="Vvar1364_DataMessaggio_anySimpleType" select="."/>
								<DTTM.1>
									<xsl:value-of select="substring(string($Vvar1364_DataMessaggio_anySimpleType), number(1), number(4))"/>
								</DTTM.1>
							</xsl:for-each>
						</xsl:for-each>
						<xsl:for-each select="DatiCalcolati">
							<xsl:for-each select="DataMessaggio">
								<xsl:variable name="Vvar1374_DataMessaggio_anySimpleType" select="."/>
								<DTTM.2>
									<xsl:value-of select="substring(string($Vvar1374_DataMessaggio_anySimpleType), number(5), number(2))"/>
								</DTTM.2>
							</xsl:for-each>
						</xsl:for-each>
						<xsl:for-each select="DatiCalcolati">
							<xsl:for-each select="DataMessaggio">
								<xsl:variable name="Vvar1384_DataMessaggio_anySimpleType" select="."/>
								<DTTM.3>
									<xsl:value-of select="substring(string($Vvar1384_DataMessaggio_anySimpleType), number(7), number(2))"/>
								</DTTM.3>
							</xsl:for-each>
						</xsl:for-each>
						<xsl:for-each select="DatiCalcolati">
							<xsl:for-each select="DataMessaggio">
								<xsl:variable name="Vvar1394_DataMessaggio_anySimpleType" select="."/>
								<DTTM.4>
									<xsl:value-of select="substring(string($Vvar1394_DataMessaggio_anySimpleType), number(9), number(2))"/>
								</DTTM.4>
							</xsl:for-each>
						</xsl:for-each>
						<xsl:for-each select="DatiCalcolati">
							<xsl:for-each select="DataMessaggio">
								<xsl:variable name="Vvar1404_DataMessaggio_anySimpleType" select="."/>
								<DTTM.5>
									<xsl:value-of select="substring(string($Vvar1404_DataMessaggio_anySimpleType), number(11), number(2))"/>
								</DTTM.5>
							</xsl:for-each>
						</xsl:for-each>
						<xsl:for-each select="DatiCalcolati">
							<xsl:for-each select="DataMessaggio">
								<xsl:variable name="Vvar1414_DataMessaggio_anySimpleType" select="."/>
								<DTTM.6>
									<xsl:value-of select="substring(string($Vvar1414_DataMessaggio_anySimpleType), number(13), number(2))"/>
								</DTTM.6>
							</xsl:for-each>
						</xsl:for-each>
					</TS.1>
				</EVN.2>
			</EVN>
			<xsl:variable name="Vvar290_const" select="'00'"/>
			<xsl:variable name="Vvar484_const" select="''"/>
			<xsl:variable name="Vvar1669_const" select="3"/>
			<PID>
				<PID.3>
					<xsl:for-each select="MainQuery">
						<xsl:for-each select="sianc.paziente.PazienteBean">
							<xsl:for-each select="codiceFiscale">
								<xsl:variable name="Vvar1428_codiceFiscale_anySimpleType" select="."/>
								<CX.1>
									<xsl:value-of select="$Vvar1428_codiceFiscale_anySimpleType"/>
								</CX.1>
							</xsl:for-each>
						</xsl:for-each>
					</xsl:for-each>
					<xsl:for-each select="DatiFissi">
						<xsl:for-each select="AuthorityCodFisc">
							<xsl:variable name="Vvar1435_AuthorityCodFisc_anySimpleType" select="."/>
							<CX.5>
								<xsl:value-of select="$Vvar1435_AuthorityCodFisc_anySimpleType"/>
							</CX.5>
						</xsl:for-each>
					</xsl:for-each>
				</PID.3>
				<PID.3>
					<xsl:for-each select="MainQuery">
						<xsl:for-each select="sianc.paziente.PazienteBean">
							<xsl:for-each select="codiceSTP">
								<xsl:variable name="Vvar1444_codiceSTP_anySimpleType" select="."/>
								<CX.1>
									<xsl:value-of select="$Vvar1444_codiceSTP_anySimpleType"/>
								</CX.1>
							</xsl:for-each>
						</xsl:for-each>
					</xsl:for-each>
					<xsl:for-each select="DatiFissi">
						<xsl:for-each select="AuthoritySTP">
							<xsl:variable name="Vvar1451_AuthoritySTP_anySimpleType" select="."/>
							<CX.5>
								<xsl:value-of select="$Vvar1451_AuthoritySTP_anySimpleType"/>
							</CX.5>
						</xsl:for-each>
					</xsl:for-each>
					<CX.8>
						<TS.1>
							<xsl:for-each select="MainQuery">
								<xsl:for-each select="sianc.paziente.PazienteBean">
									<xsl:for-each select="scadenzaSTP">
										<xsl:variable name="Vvar1458_scadenzaSTP_anySimpleType" select="."/>
										<DTTM.1>
											<xsl:value-of select="substring(string($Vvar1458_scadenzaSTP_anySimpleType), number(1), number(4))"/>
										</DTTM.1>
									</xsl:for-each>
								</xsl:for-each>
							</xsl:for-each>
							<xsl:for-each select="MainQuery">
								<xsl:for-each select="sianc.paziente.PazienteBean">
									<xsl:for-each select="scadenzaSTP">
										<xsl:variable name="Vvar1470_scadenzaSTP_anySimpleType" select="."/>
										<DTTM.2>
											<xsl:value-of select="substring(string($Vvar1470_scadenzaSTP_anySimpleType), number(5), number(2))"/>
										</DTTM.2>
									</xsl:for-each>
								</xsl:for-each>
							</xsl:for-each>
							<xsl:for-each select="MainQuery">
								<xsl:for-each select="sianc.paziente.PazienteBean">
									<xsl:for-each select="scadenzaSTP">
										<xsl:variable name="Vvar1482_scadenzaSTP_anySimpleType" select="."/>
										<DTTM.3>
											<xsl:value-of select="substring(string($Vvar1482_scadenzaSTP_anySimpleType), number(7), number(2))"/>
										</DTTM.3>
									</xsl:for-each>
								</xsl:for-each>
							</xsl:for-each>
							<DTTM.4>
								<xsl:value-of select="$Vvar290_const"/>
							</DTTM.4>
							<DTTM.5>
								<xsl:value-of select="$Vvar290_const"/>
							</DTTM.5>
						</TS.1>
					</CX.8>
				</PID.3>
				<PID.3>
					<xsl:for-each select="MainQuery">
						<xsl:for-each select="sianc.paziente.PazienteBean">
							<xsl:for-each select="numeroTesseraSanitaria">
								<xsl:variable name="Vvar1496_numeroTesseraSanitaria_anySimpleType" select="."/>
								<CX.1>
									<xsl:value-of select="$Vvar1496_numeroTesseraSanitaria_anySimpleType"/>
								</CX.1>
							</xsl:for-each>
						</xsl:for-each>
					</xsl:for-each>
					<xsl:for-each select="DatiFissi">
						<xsl:for-each select="AuthorityTessSan">
							<xsl:variable name="Vvar1503_AuthorityTessSan_anySimpleType" select="."/>
							<CX.5>
								<xsl:value-of select="$Vvar1503_AuthorityTessSan_anySimpleType"/>
							</CX.5>
						</xsl:for-each>
					</xsl:for-each>
				</PID.3>
				<PID.3>
					<xsl:for-each select="MainQuery">
						<xsl:for-each select="sianc.paziente.PazienteBean">
							<xsl:for-each select="tesseraTeam">
								<xsl:variable name="Vvar1512_tesseraTeam_anySimpleType" select="."/>
								<CX.1>
									<xsl:value-of select="$Vvar1512_tesseraTeam_anySimpleType"/>
								</CX.1>
							</xsl:for-each>
						</xsl:for-each>
					</xsl:for-each>
					<xsl:for-each select="DatiFissi">
						<xsl:for-each select="AuthorityTeam">
							<xsl:variable name="Vvar1519_AuthorityTeam_anySimpleType" select="."/>
							<CX.5>
								<xsl:value-of select="$Vvar1519_AuthorityTeam_anySimpleType"/>
							</CX.5>
						</xsl:for-each>
					</xsl:for-each>
					<CX.8>
						<TS.1>
							<xsl:for-each select="MainQuery">
								<xsl:for-each select="sianc.paziente.PazienteBean">
									<xsl:for-each select="scadenzaTesseraTeam">
										<xsl:variable name="Vvar1526_scadenzaTesseraTeam_anySimpleType" select="."/>
										<DTTM.1>
											<xsl:value-of select="substring(string($Vvar1526_scadenzaTesseraTeam_anySimpleType), number(1), number(4))"/>
										</DTTM.1>
									</xsl:for-each>
								</xsl:for-each>
							</xsl:for-each>
							<xsl:for-each select="MainQuery">
								<xsl:for-each select="sianc.paziente.PazienteBean">
									<xsl:for-each select="scadenzaTesseraTeam">
										<xsl:variable name="Vvar1538_scadenzaTesseraTeam_anySimpleType" select="."/>
										<DTTM.2>
											<xsl:value-of select="substring(string($Vvar1538_scadenzaTesseraTeam_anySimpleType), number(5), number(2))"/>
										</DTTM.2>
									</xsl:for-each>
								</xsl:for-each>
							</xsl:for-each>
							<xsl:for-each select="MainQuery">
								<xsl:for-each select="sianc.paziente.PazienteBean">
									<xsl:for-each select="scadenzaTesseraTeam">
										<xsl:variable name="Vvar1550_scadenzaTesseraTeam_anySimpleType" select="."/>
										<DTTM.3>
											<xsl:value-of select="substring(string($Vvar1550_scadenzaTesseraTeam_anySimpleType), number(7), number(2))"/>
										</DTTM.3>
									</xsl:for-each>
								</xsl:for-each>
							</xsl:for-each>
							<DTTM.4>
								<xsl:value-of select="$Vvar290_const"/>
							</DTTM.4>
							<DTTM.5>
								<xsl:value-of select="$Vvar290_const"/>
							</DTTM.5>
						</TS.1>
					</CX.8>
				</PID.3>
				<PID.3>
					<xsl:for-each select="MainQuery">
						<xsl:for-each select="sianc.paziente.PazienteBean">
							<xsl:for-each select="idPaziente">
								<xsl:variable name="Vvar1564_idPaziente_anySimpleType" select="."/>
								<CX.1>
									<xsl:value-of select="$Vvar1564_idPaziente_anySimpleType"/>
								</CX.1>
							</xsl:for-each>
						</xsl:for-each>
					</xsl:for-each>
					<xsl:for-each select="DatiFissi">
						<xsl:for-each select="AuthorityAnagCentrale">
							<xsl:variable name="Vvar1571_AuthorityAnagCentrale_anySimpleType" select="."/>
							<CX.5>
								<xsl:value-of select="$Vvar1571_AuthorityAnagCentrale_anySimpleType"/>
							</CX.5>
						</xsl:for-each>
					</xsl:for-each>
				</PID.3>
				<PID.3>
					<xsl:for-each select="MainQuery">
						<xsl:for-each select="sianc.paziente.PazienteBean">
							<xsl:for-each select="idPaziente">
								<xsl:variable name="Vvar1580_idPaziente_anySimpleType" select="."/>
								<CX.1>
									<xsl:value-of select="$Vvar1580_idPaziente_anySimpleType"/>
								</CX.1>
							</xsl:for-each>
						</xsl:for-each>
					</xsl:for-each>
					<xsl:for-each select="DatiFissi">
						<xsl:for-each select="AuthorityAnagLocale">
							<xsl:variable name="Vvar1587_AuthorityAnagLocale_anySimpleType" select="."/>
							<CX.5>
								<xsl:value-of select="$Vvar1587_AuthorityAnagLocale_anySimpleType"/>
							</CX.5>
						</xsl:for-each>
					</xsl:for-each>
				</PID.3>
				<PID.5>
					<xsl:for-each select="MainQuery">
						<xsl:for-each select="sianc.paziente.PazienteBean">
							<xsl:for-each select="cognomePaziente">
								<xsl:variable name="Vvar1596_cognomePaziente_anySimpleType" select="."/>
								<XPN.1>
									<xsl:value-of select="$Vvar1596_cognomePaziente_anySimpleType"/>
								</XPN.1>
							</xsl:for-each>
						</xsl:for-each>
					</xsl:for-each>
					<xsl:for-each select="MainQuery">
						<xsl:for-each select="sianc.paziente.PazienteBean">
							<xsl:for-each select="nomePaziente">
								<xsl:variable name="Vvar1605_nomePaziente_anySimpleType" select="."/>
								<XPN.2>
									<xsl:value-of select="$Vvar1605_nomePaziente_anySimpleType"/>
								</XPN.2>
							</xsl:for-each>
						</xsl:for-each>
					</xsl:for-each>
				</PID.5>
				<PID.7>
					<TS.1>
						<xsl:for-each select="MainQuery">
							<xsl:for-each select="sianc.paziente.PazienteBean">
								<xsl:for-each select="dataNascita">
									<xsl:variable name="Vvar1612_dataNascita_anySimpleType" select="."/>
									<DTTM.1>
										<xsl:value-of select="substring(string($Vvar1612_dataNascita_anySimpleType), number(1), number(4))"/>
									</DTTM.1>
								</xsl:for-each>
							</xsl:for-each>
						</xsl:for-each>
						<xsl:for-each select="MainQuery">
							<xsl:for-each select="sianc.paziente.PazienteBean">
								<xsl:for-each select="dataNascita">
									<xsl:variable name="Vvar1624_dataNascita_anySimpleType" select="."/>
									<DTTM.2>
										<xsl:value-of select="substring(string($Vvar1624_dataNascita_anySimpleType), number(5), number(2))"/>
									</DTTM.2>
								</xsl:for-each>
							</xsl:for-each>
						</xsl:for-each>
						<xsl:for-each select="MainQuery">
							<xsl:for-each select="sianc.paziente.PazienteBean">
								<xsl:for-each select="dataNascita">
									<xsl:variable name="Vvar1636_dataNascita_anySimpleType" select="."/>
									<DTTM.3>
										<xsl:value-of select="substring(string($Vvar1636_dataNascita_anySimpleType), number(7), number(2))"/>
									</DTTM.3>
								</xsl:for-each>
							</xsl:for-each>
						</xsl:for-each>
						<DTTM.4>
							<xsl:value-of select="$Vvar484_const"/>
						</DTTM.4>
						<DTTM.5>
							<xsl:value-of select="$Vvar484_const"/>
						</DTTM.5>
						<DTTM.6>
							<xsl:value-of select="$Vvar484_const"/>
						</DTTM.6>
					</TS.1>
				</PID.7>
				<xsl:for-each select="MainQuery">
					<xsl:for-each select="sianc.paziente.PazienteBean">
						<xsl:for-each select="sesso">
							<xsl:variable name="Vvar1650_sesso_anySimpleType" select="."/>
							<PID.8>
								<xsl:value-of select="$Vvar1650_sesso_anySimpleType"/>
							</PID.8>
						</xsl:for-each>
					</xsl:for-each>
				</xsl:for-each>
				<PID.11>
					<xsl:for-each select="MainQuery">
						<xsl:for-each select="sianc.paziente.PazienteBean">
							<xsl:for-each select="codiceISTATComuneNascita">
								<xsl:variable name="Vvar1659_codiceISTATComuneNascita_anySimpleType" select="."/>
								<XAD.3>
									<xsl:value-of select="$Vvar1659_codiceISTATComuneNascita_anySimpleType"/>
								</XAD.3>
							</xsl:for-each>
						</xsl:for-each>
					</xsl:for-each>
					<xsl:for-each select="MainQuery">
						<xsl:for-each select="sianc.paziente.PazienteBean">
							<xsl:for-each select="codiceISTATComuneNascita">
								<xsl:variable name="Vvar1666_codiceISTATComuneNascita_anySimpleType" select="."/>
								<xsl:variable name="Vvar1672_result_equal" select="(substring(string($Vvar1666_codiceISTATComuneNascita_anySimpleType), number(1), number($Vvar1669_const))) = ('999')"/>
								<xsl:variable name="Vvar1673_cond">
									<xsl:choose>
										<xsl:when test="(string($Vvar1672_result_equal))='true'">
											<xsl:value-of select="substring(string($Vvar1666_codiceISTATComuneNascita_anySimpleType), number('4'), number($Vvar1669_const))"/>
										</xsl:when>
										<xsl:otherwise>
											<xsl:value-of select="'100'"/>
										</xsl:otherwise>
									</xsl:choose>
								</xsl:variable>
								<XAD.6>
									<xsl:value-of select="$Vvar1673_cond"/>
								</XAD.6>
							</xsl:for-each>
						</xsl:for-each>
					</xsl:for-each>
					<xsl:for-each select="DatiFissi">
						<xsl:for-each select="AuthorityNascita">
							<xsl:variable name="Vvar1684_AuthorityNascita_anySimpleType" select="."/>
							<XAD.7>
								<xsl:value-of select="$Vvar1684_AuthorityNascita_anySimpleType"/>
							</XAD.7>
						</xsl:for-each>
					</xsl:for-each>
				</PID.11>
				<PID.11>
					<XAD.1>
						<xsl:for-each select="MainQuery">
							<xsl:for-each select="sianc.paziente.PazienteBean">
								<xsl:for-each select="indirizzoResidenza">
									<xsl:variable name="Vvar1693_indirizzoResidenza_anySimpleType" select="."/>
									<SAD.1>
										<xsl:value-of select="$Vvar1693_indirizzoResidenza_anySimpleType"/>
									</SAD.1>
								</xsl:for-each>
							</xsl:for-each>
						</xsl:for-each>
						<SAD.2>
							<xsl:value-of select="$Vvar484_const"/>
						</SAD.2>
						<xsl:for-each select="MainQuery">
							<xsl:for-each select="sianc.paziente.PazienteBean">
								<xsl:for-each select="numeroCivicoResidenza">
									<xsl:variable name="Vvar1702_numeroCivicoResidenza_anySimpleType" select="."/>
									<SAD.3>
										<xsl:value-of select="$Vvar1702_numeroCivicoResidenza_anySimpleType"/>
									</SAD.3>
								</xsl:for-each>
							</xsl:for-each>
						</xsl:for-each>
					</XAD.1>
					<xsl:for-each select="MainQuery">
						<xsl:for-each select="sianc.paziente.PazienteBean">
							<xsl:for-each select="codiceISTATComuneResidenza">
								<xsl:variable name="Vvar1711_codiceISTATComuneResidenza_anySimpleType" select="."/>
								<XAD.3>
									<xsl:value-of select="$Vvar1711_codiceISTATComuneResidenza_anySimpleType"/>
								</XAD.3>
							</xsl:for-each>
						</xsl:for-each>
					</xsl:for-each>
					<xsl:for-each select="MainQuery">
						<xsl:for-each select="sianc.paziente.PazienteBean">
							<xsl:for-each select="capResidenza">
								<xsl:variable name="Vvar1720_capResidenza_anySimpleType" select="."/>
								<XAD.5>
									<xsl:value-of select="$Vvar1720_capResidenza_anySimpleType"/>
								</XAD.5>
							</xsl:for-each>
						</xsl:for-each>
					</xsl:for-each>
					<xsl:for-each select="DatiFissi">
						<xsl:for-each select="AuthorityResidenza">
							<xsl:variable name="Vvar1727_AuthorityResidenza_anySimpleType" select="."/>
							<XAD.7>
								<xsl:value-of select="$Vvar1727_AuthorityResidenza_anySimpleType"/>
							</XAD.7>
						</xsl:for-each>
					</xsl:for-each>
				</PID.11>
				<PID.11>
					<XAD.1>
						<xsl:for-each select="MainQuery">
							<xsl:for-each select="sianc.paziente.PazienteBean">
								<xsl:for-each select="indirizzoDomicilio">
									<xsl:variable name="Vvar1736_indirizzoDomicilio_anySimpleType" select="."/>
									<SAD.1>
										<xsl:value-of select="$Vvar1736_indirizzoDomicilio_anySimpleType"/>
									</SAD.1>
								</xsl:for-each>
							</xsl:for-each>
						</xsl:for-each>
						<SAD.2>
							<xsl:value-of select="$Vvar484_const"/>
						</SAD.2>
						<xsl:for-each select="MainQuery">
							<xsl:for-each select="sianc.paziente.PazienteBean">
								<xsl:for-each select="numeroCivicoDomicilio">
									<xsl:variable name="Vvar1745_numeroCivicoDomicilio_anySimpleType" select="."/>
									<SAD.3>
										<xsl:value-of select="$Vvar1745_numeroCivicoDomicilio_anySimpleType"/>
									</SAD.3>
								</xsl:for-each>
							</xsl:for-each>
						</xsl:for-each>
					</XAD.1>
					<xsl:for-each select="MainQuery">
						<xsl:for-each select="sianc.paziente.PazienteBean">
							<xsl:for-each select="codiceISTATComuneDomicilio">
								<xsl:variable name="Vvar1754_codiceISTATComuneDomicilio_anySimpleType" select="."/>
								<XAD.3>
									<xsl:value-of select="$Vvar1754_codiceISTATComuneDomicilio_anySimpleType"/>
								</XAD.3>
							</xsl:for-each>
						</xsl:for-each>
					</xsl:for-each>
					<xsl:for-each select="MainQuery">
						<xsl:for-each select="sianc.paziente.PazienteBean">
							<xsl:for-each select="capDomicilio">
								<xsl:variable name="Vvar1763_capDomicilio_anySimpleType" select="."/>
								<XAD.5>
									<xsl:value-of select="$Vvar1763_capDomicilio_anySimpleType"/>
								</XAD.5>
							</xsl:for-each>
						</xsl:for-each>
					</xsl:for-each>
					<xsl:for-each select="DatiFissi">
						<xsl:for-each select="AuthorityDomicilio">
							<xsl:variable name="Vvar1770_AuthorityDomicilio_anySimpleType" select="."/>
							<XAD.7>
								<xsl:value-of select="$Vvar1770_AuthorityDomicilio_anySimpleType"/>
							</XAD.7>
						</xsl:for-each>
					</xsl:for-each>
				</PID.11>
				<PID.13>
					<xsl:for-each select="MainQuery">
						<xsl:for-each select="sianc.paziente.PazienteBean">
							<xsl:for-each select="numeroTelefono1">
								<xsl:variable name="Vvar1779_numeroTelefono1_anySimpleType" select="."/>
								<XTN.12>
									<xsl:value-of select="$Vvar1779_numeroTelefono1_anySimpleType"/>
								</XTN.12>
							</xsl:for-each>
						</xsl:for-each>
					</xsl:for-each>
				</PID.13>
				<PID.13>
					<xsl:for-each select="MainQuery">
						<xsl:for-each select="sianc.paziente.PazienteBean">
							<xsl:for-each select="numeroTelefono2">
								<xsl:variable name="Vvar1788_numeroTelefono2_anySimpleType" select="."/>
								<XTN.12>
									<xsl:value-of select="$Vvar1788_numeroTelefono2_anySimpleType"/>
								</XTN.12>
							</xsl:for-each>
						</xsl:for-each>
					</xsl:for-each>
				</PID.13>
				<PID.13>
					<xsl:for-each select="MainQuery">
						<xsl:for-each select="sianc.paziente.PazienteBean">
							<xsl:for-each select="numeroTelefono3">
								<XTN.1/>
							</xsl:for-each>
						</xsl:for-each>
					</xsl:for-each>
				</PID.13>
				<PID.26>
					<xsl:for-each select="MainQuery">
						<xsl:for-each select="sianc.paziente.PazienteBean">
							<xsl:for-each select="codiceCittadinanza">
								<xsl:variable name="Vvar1804_codiceCittadinanza_anySimpleType" select="."/>
								<CE.1>
									<xsl:value-of select="$Vvar1804_codiceCittadinanza_anySimpleType"/>
								</CE.1>
							</xsl:for-each>
						</xsl:for-each>
					</xsl:for-each>
				</PID.26>
				<PID.29>
					<TS.1>
						<xsl:for-each select="MainQuery">
							<xsl:for-each select="sianc.paziente.PazienteBean">
								<xsl:for-each select="dataDecesso">
									<xsl:variable name="Vvar1811_dataDecesso_anySimpleType" select="."/>
									<DTTM.1>
										<xsl:value-of select="substring(string($Vvar1811_dataDecesso_anySimpleType), number(1), number(4))"/>
									</DTTM.1>
								</xsl:for-each>
							</xsl:for-each>
						</xsl:for-each>
						<xsl:for-each select="MainQuery">
							<xsl:for-each select="sianc.paziente.PazienteBean">
								<xsl:for-each select="dataDecesso">
									<xsl:variable name="Vvar1823_dataDecesso_anySimpleType" select="."/>
									<DTTM.2>
										<xsl:value-of select="substring(string($Vvar1823_dataDecesso_anySimpleType), number(5), number(2))"/>
									</DTTM.2>
								</xsl:for-each>
							</xsl:for-each>
						</xsl:for-each>
						<xsl:for-each select="MainQuery">
							<xsl:for-each select="sianc.paziente.PazienteBean">
								<xsl:for-each select="dataDecesso">
									<xsl:variable name="Vvar1835_dataDecesso_anySimpleType" select="."/>
									<DTTM.3>
										<xsl:value-of select="substring(string($Vvar1835_dataDecesso_anySimpleType), number(7), number(2))"/>
									</DTTM.3>
								</xsl:for-each>
							</xsl:for-each>
						</xsl:for-each>
						<DTTM.4>
							<xsl:value-of select="$Vvar290_const"/>
						</DTTM.4>
						<DTTM.5>
							<xsl:value-of select="$Vvar290_const"/>
						</DTTM.5>
					</TS.1>
				</PID.29>
			</PID>
			<xsl:variable name="ExistsResult">
				<xsl:for-each select="MainQuery">
					<xsl:for-each select="AH_MODA_DIM_ID">
						<xsl:value-of select="true()"/>
					</xsl:for-each>
				</xsl:for-each>
			</xsl:variable>
			<xsl:variable name="Vvar901_exists" select="string-length( $ExistsResult )&gt;0"/>
			<xsl:variable name="Vvar910_cond">
				<xsl:choose>
					<xsl:when test="(string($Vvar901_exists))='true'">
						<xsl:for-each select="MainQuery">
							<xsl:for-each select="AH_DT_EVENTOC">
								<xsl:variable name="Vvar1981_AH_DT_EVENTOC_anySimpleType" select="."/>
								<xsl:value-of select="string($Vvar1981_AH_DT_EVENTOC_anySimpleType)"/>
							</xsl:for-each>
						</xsl:for-each>
					</xsl:when>
					<xsl:otherwise/>
				</xsl:choose>
			</xsl:variable>
			<xsl:variable name="ExistsResult1">
				<xsl:for-each select="MainQuery">
					<xsl:for-each select="AH_MODA_DIM_ID">
						<xsl:value-of select="true()"/>
					</xsl:for-each>
				</xsl:for-each>
			</xsl:variable>
			<xsl:variable name="Vvar923_exists" select="string-length( $ExistsResult1 )&gt;0"/>
			<xsl:variable name="Vvar932_cond">
				<xsl:choose>
					<xsl:when test="(string($Vvar923_exists))='true'">
						<xsl:for-each select="MainQuery">
							<xsl:for-each select="AH_DT_EVENTOC">
								<xsl:variable name="Vvar1993_AH_DT_EVENTOC_anySimpleType" select="."/>
								<xsl:value-of select="string($Vvar1993_AH_DT_EVENTOC_anySimpleType)"/>
							</xsl:for-each>
						</xsl:for-each>
					</xsl:when>
					<xsl:otherwise/>
				</xsl:choose>
			</xsl:variable>
			<xsl:variable name="ExistsResult2">
				<xsl:for-each select="MainQuery">
					<xsl:for-each select="AH_MODA_DIM_ID">
						<xsl:value-of select="true()"/>
					</xsl:for-each>
				</xsl:for-each>
			</xsl:variable>
			<xsl:variable name="Vvar945_exists" select="string-length( $ExistsResult2 )&gt;0"/>
			<xsl:variable name="Vvar954_cond">
				<xsl:choose>
					<xsl:when test="(string($Vvar945_exists))='true'">
						<xsl:for-each select="MainQuery">
							<xsl:for-each select="AH_DT_EVENTOC">
								<xsl:variable name="Vvar2005_AH_DT_EVENTOC_anySimpleType" select="."/>
								<xsl:value-of select="string($Vvar2005_AH_DT_EVENTOC_anySimpleType)"/>
							</xsl:for-each>
						</xsl:for-each>
					</xsl:when>
					<xsl:otherwise/>
				</xsl:choose>
			</xsl:variable>
			<xsl:variable name="ExistsResult3">
				<xsl:for-each select="MainQuery">
					<xsl:for-each select="AH_MODA_DIM_ID">
						<xsl:value-of select="true()"/>
					</xsl:for-each>
				</xsl:for-each>
			</xsl:variable>
			<xsl:variable name="Vvar967_exists" select="string-length( $ExistsResult3 )&gt;0"/>
			<xsl:variable name="Vvar976_cond">
				<xsl:choose>
					<xsl:when test="(string($Vvar967_exists))='true'">
						<xsl:for-each select="MainQuery">
							<xsl:for-each select="AH_DT_EVENTOC">
								<xsl:variable name="Vvar2017_AH_DT_EVENTOC_anySimpleType" select="."/>
								<xsl:value-of select="string($Vvar2017_AH_DT_EVENTOC_anySimpleType)"/>
							</xsl:for-each>
						</xsl:for-each>
					</xsl:when>
					<xsl:otherwise/>
				</xsl:choose>
			</xsl:variable>
			<xsl:variable name="ExistsResult4">
				<xsl:for-each select="MainQuery">
					<xsl:for-each select="AH_MODA_DIM_ID">
						<xsl:value-of select="true()"/>
					</xsl:for-each>
				</xsl:for-each>
			</xsl:variable>
			<xsl:variable name="Vvar989_exists" select="string-length( $ExistsResult4 )&gt;0"/>
			<xsl:variable name="Vvar998_cond">
				<xsl:choose>
					<xsl:when test="(string($Vvar989_exists))='true'">
						<xsl:for-each select="MainQuery">
							<xsl:for-each select="AH_DT_EVENTOC">
								<xsl:variable name="Vvar2029_AH_DT_EVENTOC_anySimpleType" select="."/>
								<xsl:value-of select="string($Vvar2029_AH_DT_EVENTOC_anySimpleType)"/>
							</xsl:for-each>
						</xsl:for-each>
					</xsl:when>
					<xsl:otherwise/>
				</xsl:choose>
			</xsl:variable>
			<xsl:variable name="ExistsResult5">
				<xsl:for-each select="MainQuery">
					<xsl:for-each select="AH_MODA_DIM_ID">
						<xsl:value-of select="true()"/>
					</xsl:for-each>
				</xsl:for-each>
			</xsl:variable>
			<xsl:variable name="Vvar1011_exists" select="string-length( $ExistsResult5 )&gt;0"/>
			<xsl:variable name="Vvar1020_cond">
				<xsl:choose>
					<xsl:when test="(string($Vvar1011_exists))='true'">
						<xsl:for-each select="MainQuery">
							<xsl:for-each select="AH_DT_EVENTOC">
								<xsl:variable name="Vvar2041_AH_DT_EVENTOC_anySimpleType" select="."/>
								<xsl:value-of select="string($Vvar2041_AH_DT_EVENTOC_anySimpleType)"/>
							</xsl:for-each>
						</xsl:for-each>
					</xsl:when>
					<xsl:otherwise/>
				</xsl:choose>
			</xsl:variable>
			<PV1>
				<xsl:for-each select="DatiFissi">
					<xsl:for-each select="TipoAccesso">
						<xsl:variable name="Vvar1847_TipoAccesso_anySimpleType" select="."/>
						<PV1.2>
							<xsl:value-of select="$Vvar1847_TipoAccesso_anySimpleType"/>
						</PV1.2>
					</xsl:for-each>
				</xsl:for-each>
				<PV1.3>
					<xsl:for-each select="DatiCalcolati">
						<xsl:for-each select="MatricolaUP">
							<xsl:variable name="Vvar1854_MatricolaUP_anySimpleType" select="."/>
							<PL.1>
								<xsl:value-of select="$Vvar1854_MatricolaUP_anySimpleType"/>
							</PL.1>
						</xsl:for-each>
					</xsl:for-each>
					<PL.4>
						<xsl:for-each select="DatiCalcolati">
							<xsl:for-each select="StruttSan">
								<xsl:variable name="Vvar1861_StruttSan_anySimpleType" select="."/>
								<HD.1>
									<xsl:value-of select="$Vvar1861_StruttSan_anySimpleType"/>
								</HD.1>
							</xsl:for-each>
						</xsl:for-each>
						<xsl:for-each select="DatiCalcolati">
							<xsl:for-each select="UO">
								<xsl:variable name="Vvar1868_UO_anySimpleType" select="."/>
								<HD.2>
									<xsl:value-of select="$Vvar1868_UO_anySimpleType"/>
								</HD.2>
							</xsl:for-each>
						</xsl:for-each>
					</PL.4>
				</PV1.3>
				<PV1.6>
					<xsl:for-each select="DatiCalcolati">
						<xsl:for-each select="MatricolaUPPrec">
							<xsl:variable name="Vvar1875_MatricolaUPPrec_anySimpleType" select="."/>
							<PL.1>
								<xsl:value-of select="$Vvar1875_MatricolaUPPrec_anySimpleType"/>
							</PL.1>
						</xsl:for-each>
					</xsl:for-each>
					<PL.4>
						<xsl:for-each select="DatiCalcolati">
							<xsl:for-each select="StruttSanPrec">
								<xsl:variable name="Vvar1882_StruttSanPrec_anySimpleType" select="."/>
								<HD.1>
									<xsl:value-of select="$Vvar1882_StruttSanPrec_anySimpleType"/>
								</HD.1>
							</xsl:for-each>
						</xsl:for-each>
						<xsl:for-each select="DatiCalcolati">
							<xsl:for-each select="UOPrec">
								<xsl:variable name="Vvar1889_UOPrec_anySimpleType" select="."/>
								<HD.2>
									<xsl:value-of select="$Vvar1889_UOPrec_anySimpleType"/>
								</HD.2>
							</xsl:for-each>
						</xsl:for-each>
					</PL.4>
				</PV1.6>
				<PV1.19>
					<xsl:for-each select="MainQuery">
						<xsl:for-each select="AH_CODNOSO">
							<xsl:variable name="Vvar1896_AH_CODNOSO_anySimpleType" select="."/>
							<CX.1>
								<xsl:value-of select="$Vvar1896_AH_CODNOSO_anySimpleType"/>
							</CX.1>
						</xsl:for-each>
					</xsl:for-each>
					<xsl:for-each select="DatiFissi">
						<xsl:for-each select="AuthorityIdentificativo">
							<xsl:variable name="Vvar1903_AuthorityIdentificativo_anySimpleType" select="."/>
							<CX.5>
								<xsl:value-of select="$Vvar1903_AuthorityIdentificativo_anySimpleType"/>
							</CX.5>
						</xsl:for-each>
					</xsl:for-each>
				</PV1.19>
				<xsl:for-each select="MainQuery">
					<xsl:for-each select="AH_MODA_DIM_ID">
						<xsl:variable name="Vvar1910_AH_MODA_DIM_ID_anySimpleType" select="."/>
						<PV1.36>
							<xsl:value-of select="$Vvar1910_AH_MODA_DIM_ID_anySimpleType"/>
						</PV1.36>
					</xsl:for-each>
				</xsl:for-each>
				<PV1.44>
					<TS.1>
						<xsl:for-each select="MainQuery">
							<xsl:for-each select="AH_DT_CONTATTOC">
								<xsl:variable name="Vvar1915_AH_DT_CONTATTOC_anySimpleType" select="."/>
								<DTTM.1>
									<xsl:value-of select="substring(string($Vvar1915_AH_DT_CONTATTOC_anySimpleType), number(1), number(4))"/>
								</DTTM.1>
							</xsl:for-each>
						</xsl:for-each>
						<xsl:for-each select="MainQuery">
							<xsl:for-each select="AH_DT_CONTATTOC">
								<xsl:variable name="Vvar1925_AH_DT_CONTATTOC_anySimpleType" select="."/>
								<DTTM.2>
									<xsl:value-of select="substring(string($Vvar1925_AH_DT_CONTATTOC_anySimpleType), number(5), number(2))"/>
								</DTTM.2>
							</xsl:for-each>
						</xsl:for-each>
						<xsl:for-each select="MainQuery">
							<xsl:for-each select="AH_DT_CONTATTOC">
								<xsl:variable name="Vvar1935_AH_DT_CONTATTOC_anySimpleType" select="."/>
								<DTTM.3>
									<xsl:value-of select="substring(string($Vvar1935_AH_DT_CONTATTOC_anySimpleType), number(7), number(2))"/>
								</DTTM.3>
							</xsl:for-each>
						</xsl:for-each>
						<xsl:for-each select="MainQuery">
							<xsl:for-each select="AH_DT_CONTATTOC">
								<xsl:variable name="Vvar1945_AH_DT_CONTATTOC_anySimpleType" select="."/>
								<DTTM.4>
									<xsl:value-of select="substring(string($Vvar1945_AH_DT_CONTATTOC_anySimpleType), number(9), number(2))"/>
								</DTTM.4>
							</xsl:for-each>
						</xsl:for-each>
						<xsl:for-each select="MainQuery">
							<xsl:for-each select="AH_DT_CONTATTOC">
								<xsl:variable name="Vvar1955_AH_DT_CONTATTOC_anySimpleType" select="."/>
								<DTTM.5>
									<xsl:value-of select="substring(string($Vvar1955_AH_DT_CONTATTOC_anySimpleType), number(11), number(2))"/>
								</DTTM.5>
							</xsl:for-each>
						</xsl:for-each>
						<xsl:for-each select="MainQuery">
							<xsl:for-each select="AH_DT_CONTATTOC">
								<xsl:variable name="Vvar1965_AH_DT_CONTATTOC_anySimpleType" select="."/>
								<DTTM.6>
									<xsl:value-of select="substring(string($Vvar1965_AH_DT_CONTATTOC_anySimpleType), number(13), number(2))"/>
								</DTTM.6>
							</xsl:for-each>
						</xsl:for-each>
					</TS.1>
				</PV1.44>
				<PV1.45>
					<TS.1>
						<DTTM.1>
							<xsl:value-of select="substring($Vvar910_cond, number(1), number(4))"/>
						</DTTM.1>
						<DTTM.2>
							<xsl:value-of select="substring($Vvar932_cond, number(5), number(2))"/>
						</DTTM.2>
						<DTTM.3>
							<xsl:value-of select="substring($Vvar954_cond, number(7), number(2))"/>
						</DTTM.3>
						<DTTM.4>
							<xsl:value-of select="substring($Vvar976_cond, number(9), number(2))"/>
						</DTTM.4>
						<DTTM.5>
							<xsl:value-of select="substring($Vvar998_cond, number(11), number(2))"/>
						</DTTM.5>
						<DTTM.6>
							<xsl:value-of select="substring($Vvar1020_cond, number(13), number(2))"/>
						</DTTM.6>
					</TS.1>
				</PV1.45>
				<PV1.50>
					<xsl:for-each select="MainQuery">
						<xsl:for-each select="AH_CODNOSO">
							<xsl:variable name="Vvar2049_AH_CODNOSO_anySimpleType" select="."/>
							<CX.1>
								<xsl:value-of select="$Vvar2049_AH_CODNOSO_anySimpleType"/>
							</CX.1>
						</xsl:for-each>
					</xsl:for-each>
					<xsl:for-each select="DatiFissi">
						<xsl:for-each select="AuthorityIdentificativo">
							<xsl:variable name="Vvar2056_AuthorityIdentificativo_anySimpleType" select="."/>
							<CX.5>
								<xsl:value-of select="$Vvar2056_AuthorityIdentificativo_anySimpleType"/>
							</CX.5>
						</xsl:for-each>
					</xsl:for-each>
				</PV1.50>
			</PV1>
			<xsl:variable name="Vvar1051_const" select="'1'"/>
			<TXA>
				<TXA.1>
					<xsl:value-of select="$Vvar1051_const"/>
				</TXA.1>
				<xsl:for-each select="DatiFissi">
					<xsl:for-each select="TipoDocumento">
						<xsl:variable name="Vvar2063_TipoDocumento_anySimpleType" select="."/>
						<TXA.2>
							<xsl:value-of select="$Vvar2063_TipoDocumento_anySimpleType"/>
						</TXA.2>
					</xsl:for-each>
				</xsl:for-each>
				<xsl:for-each select="DatiFissi">
					<xsl:for-each select="FormatoDoc">
						<xsl:variable name="Vvar2070_FormatoDoc_anySimpleType" select="."/>
						<TXA.3>
							<xsl:value-of select="$Vvar2070_FormatoDoc_anySimpleType"/>
						</TXA.3>
					</xsl:for-each>
				</xsl:for-each>
				<TXA.9>
					<xsl:for-each select="DatiCalcolati">
						<xsl:for-each select="CognomeMedDim">
							<xsl:variable name="Vvar2077_CognomeMedDim_anySimpleType" select="."/>
							<XCN.2>
								<xsl:value-of select="$Vvar2077_CognomeMedDim_anySimpleType"/>
							</XCN.2>
						</xsl:for-each>
					</xsl:for-each>
					<xsl:for-each select="DatiCalcolati">
						<xsl:for-each select="NomeMedDim">
							<xsl:variable name="Vvar2084_NomeMedDim_anySimpleType" select="."/>
							<XCN.3>
								<xsl:value-of select="$Vvar2084_NomeMedDim_anySimpleType"/>
							</XCN.3>
						</xsl:for-each>
					</xsl:for-each>
				</TXA.9>
				<TXA.12>
					<xsl:for-each select="MainQuery">
						<xsl:for-each select="AH_AT_ID">
							<xsl:variable name="Vvar2091_AH_AT_ID_anySimpleType" select="."/>
							<EI.3>
								<xsl:value-of select="$Vvar2091_AH_AT_ID_anySimpleType"/>
							</EI.3>
						</xsl:for-each>
					</xsl:for-each>
				</TXA.12>
				<TXA.13>
					<xsl:for-each select="MainQuery">
						<xsl:for-each select="AH_AT_ID_SOSTITUITO">
							<xsl:variable name="Vvar2098_AH_AT_ID_SOSTITUITO_anySimpleType" select="."/>
							<EI.3>
								<xsl:value-of select="$Vvar2098_AH_AT_ID_SOSTITUITO_anySimpleType"/>
							</EI.3>
						</xsl:for-each>
					</xsl:for-each>
				</TXA.13>
				<xsl:for-each select="DatiFissi">
					<xsl:for-each select="DocStatoVal">
						<xsl:variable name="Vvar2105_DocStatoVal_anySimpleType" select="."/>
						<TXA.17>
							<xsl:value-of select="$Vvar2105_DocStatoVal_anySimpleType"/>
						</TXA.17>
					</xsl:for-each>
				</xsl:for-each>
				<xsl:for-each select="DatiFissi">
					<xsl:for-each select="ConfidentailStatusDoc">
						<xsl:variable name="Vvar2112_ConfidentailStatusDoc_anySimpleType" select="."/>
						<TXA.18>
							<xsl:value-of select="$Vvar2112_ConfidentailStatusDoc_anySimpleType"/>
						</TXA.18>
					</xsl:for-each>
				</xsl:for-each>
				<TXA.22>
					<xsl:for-each select="DatiCalcolati">
						<xsl:for-each select="CognomeMedDim">
							<xsl:variable name="Vvar2119_CognomeMedDim_anySimpleType" select="."/>
							<PPN.2>
								<xsl:value-of select="$Vvar2119_CognomeMedDim_anySimpleType"/>
							</PPN.2>
						</xsl:for-each>
					</xsl:for-each>
					<xsl:for-each select="DatiCalcolati">
						<xsl:for-each select="NomeMedDim">
							<xsl:variable name="Vvar2126_NomeMedDim_anySimpleType" select="."/>
							<PPN.3>
								<xsl:value-of select="$Vvar2126_NomeMedDim_anySimpleType"/>
							</PPN.3>
						</xsl:for-each>
					</xsl:for-each>
					<PPN.15>
						<TS.1>
							<xsl:for-each select="MainQuery">
								<xsl:for-each select="AH_DT_EVENTOC">
									<xsl:variable name="Vvar2131_AH_DT_EVENTOC_anySimpleType" select="."/>
									<DTTM.1>
										<xsl:value-of select="substring(string($Vvar2131_AH_DT_EVENTOC_anySimpleType), number(1), number(4))"/>
									</DTTM.1>
								</xsl:for-each>
							</xsl:for-each>
							<xsl:for-each select="MainQuery">
								<xsl:for-each select="AH_DT_EVENTOC">
									<xsl:variable name="Vvar2141_AH_DT_EVENTOC_anySimpleType" select="."/>
									<DTTM.2>
										<xsl:value-of select="substring(string($Vvar2141_AH_DT_EVENTOC_anySimpleType), number(5), number(2))"/>
									</DTTM.2>
								</xsl:for-each>
							</xsl:for-each>
							<xsl:for-each select="MainQuery">
								<xsl:for-each select="AH_DT_EVENTOC">
									<xsl:variable name="Vvar2151_AH_DT_EVENTOC_anySimpleType" select="."/>
									<DTTM.3>
										<xsl:value-of select="substring(string($Vvar2151_AH_DT_EVENTOC_anySimpleType), number(7), number(2))"/>
									</DTTM.3>
								</xsl:for-each>
							</xsl:for-each>
							<xsl:for-each select="MainQuery">
								<xsl:for-each select="AH_DT_EVENTOC">
									<xsl:variable name="Vvar2161_AH_DT_EVENTOC_anySimpleType" select="."/>
									<DTTM.4>
										<xsl:value-of select="substring(string($Vvar2161_AH_DT_EVENTOC_anySimpleType), number(9), number(2))"/>
									</DTTM.4>
								</xsl:for-each>
							</xsl:for-each>
							<xsl:for-each select="MainQuery">
								<xsl:for-each select="AH_DT_EVENTOC">
									<xsl:variable name="Vvar2171_AH_DT_EVENTOC_anySimpleType" select="."/>
									<DTTM.5>
										<xsl:value-of select="substring(string($Vvar2171_AH_DT_EVENTOC_anySimpleType), number(11), number(2))"/>
									</DTTM.5>
								</xsl:for-each>
							</xsl:for-each>
							<DTTM.6>
								<xsl:value-of select="$Vvar290_const"/>
							</DTTM.6>
						</TS.1>
					</PPN.15>
				</TXA.22>
			</TXA>
			<OBX>
				<OBX.1>
					<xsl:value-of select="$Vvar1292_const"/>
				</OBX.1>
				<OBX.2>
					<xsl:value-of select="'ED'"/>
				</OBX.2>
				<OBX.3>
					<xsl:for-each select="DatiFissi">
						<xsl:for-each select="AuthorityIdentificativo">
							<xsl:variable name="Vvar2183_AuthorityIdentificativo_anySimpleType" select="."/>
							<CE.1>
								<xsl:value-of select="$Vvar2183_AuthorityIdentificativo_anySimpleType"/>
							</CE.1>
						</xsl:for-each>
					</xsl:for-each>
					<xsl:for-each select="DatiFissi">
						<xsl:for-each select="OBXSistemaCodifica">
							<xsl:variable name="Vvar2190_OBXSistemaCodifica_anySimpleType" select="."/>
							<CE.3>
								<xsl:value-of select="$Vvar2190_OBXSistemaCodifica_anySimpleType"/>
							</CE.3>
						</xsl:for-each>
					</xsl:for-each>
				</OBX.3>
				<OBX.4>
					<xsl:value-of select="$Vvar1051_const"/>
				</OBX.4>
				<OBX.5>
					<ED.2>
						<xsl:value-of select="'multipart'"/>
					</ED.2>
					<ED.3>
						<xsl:value-of select="'Octet-Stream'"/>
					</ED.3>
					<ED.4>
						<xsl:value-of select="'Base64'"/>
					</ED.4>
					<xsl:for-each select="MainQuery">
						<xsl:for-each select="AT_FILE">
							<xsl:variable name="Vvar2197_AT_FILE_anySimpleType" select="."/>
							<ED.5>
								<xsl:value-of select="$Vvar2197_AT_FILE_anySimpleType"/>
							</ED.5>
						</xsl:for-each>
					</xsl:for-each>
				</OBX.5>
				<xsl:for-each select="DatiCalcolati">
					<xsl:for-each select="TipoMessaggio">
						<xsl:variable name="Vvar2202_TipoMessaggio_anySimpleType" select="."/>
						<xsl:variable name="Vvar2205_result_equal" select="(string($Vvar2202_TipoMessaggio_anySimpleType)) = ('MDM^T02')"/>
						<xsl:variable name="Vvar2206_cond">
							<xsl:choose>
								<xsl:when test="(string($Vvar2205_result_equal))='true'">
									<xsl:value-of select="'F'"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:value-of select="'C'"/>
								</xsl:otherwise>
							</xsl:choose>
						</xsl:variable>
						<OBX.11>
							<xsl:value-of select="$Vvar2206_cond"/>
						</OBX.11>
					</xsl:for-each>
				</xsl:for-each>
			</OBX>
		</MDM_T02>
	</xsl:template>
</xsl:stylesheet>
